#!/bin/bash

if [ "$(uname)" != "Darwin" ]; then
    echo "This script only works on macOS"
    exit 0
fi

# Default values
title="Notify"
sound=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
    --message)
        message="$2"
        shift 2
        ;;
    --title)
        title="$2"
        shift 2
        ;;
    --sound)
        sound=true
        shift
        ;;
    *)
        shift
        ;;
    esac
done

if [ -z "$message" ]; then
    echo "--message argument is required"
    exit 1
fi

if [ "$sound" = true ]; then
    osascript -e "display notification \"$message\" with title \"$title\" sound name \"Glass\""
else
    osascript -e "display notification \"$message\" with title \"$title\""
fi
