#!/bin/bash

# I intentionally have not set up a corresponding production script for this.
# Maybe worth doing in the future, but I don't want to be able to easily goof it
# up.

set -eu

if [ ! -f .env.preview ]; then
    echo ".env.preview not found, you must create it and set the required environment variables."
    exit 1
fi

source .env.preview

env_vars=(
    AUTH_SECRET
    AUTH_GOOGLE_ID
    AUTH_GOOGLE_SECRET
    POSTGRES_URL
    POSTGRES_USER
    POSTGRES_HOST
    SUPABASE_JWT_SECRET
    NEXT_PUBLIC_SUPABASE_ANON_KEY
    POSTGRES_PRISMA_URL
    POSTGRES_PASSWORD
    POSTGRES_DATABASE
    SUPABASE_URL
    NEXT_PUBLIC_SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    POSTGRES_URL_NON_POOLING
)

for var in "${env_vars[@]}"; do
    value="${!var}"
    if [ -z "$value" ]; then
        echo "Warning: $var is not set in .env.preview"
        continue
    fi
    echo "$value" | pnpx vercel env add "$var" preview --force
done
